spring:
  application:
    name: openapi
  cloud:
    nacos:
      server-addr: 172.33.172.241:8848 # nacos服务地址
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moon
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: none
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
moon:
  client:
    access-key: moon
    secret-key: abcdefg
#dubbo:
#  application:
#    name: dubbo-openapi
#  protocol:
#    port: -1
#    name: dubbo
#  registry:
#    address: 192.168.88.130:8848 # Nacos地址
#    id: nacos-registry