server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=yupi, hello
            - AddRequestParameter=name, MoonLight
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
