server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 172.33.172.241:8848 # nacos服务地址
    gateway:
      default-filters:
        - AddRequestHeader=source,yupi
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
#dubbo:
#  application:
#    name: dubbo-gateway
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: 192.168.88.130:8848 # Nacos地址
#    id: nacos-registry